# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: images/selfie.jpg (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Yulong Zheng
title: Ph.D. Candidate in Physical Chemistry
email: yulong.zheng@gatech.edu
# email_title: Email (Email title override)
# phone: 4042686540
# phone_title: Phone (Phone title override)
website: Beandope.gatech.io
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: jekyllrb
github_username:  Beandope
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: ppatrickki
linkedin_username: yulong-zheng-aa71a0128
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll
google_username: pcLymh4AAAAJ&hl=en
# orcid_username: 0000-0000-0000-0000

# # Additional icon links
# additional_links:
# - title: Link name
#   icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)
# # - title: another link
# #   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
# #   url: Link url (eg. https://google.com)


# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/selfie.jpg #(eg. images/profile.jpg)
about_content: | # this will include new lines to allow paragraphs
  - Born and raised in Hubei, China. 
  - Have been to/lived in a few places around the world.
  - Always excited about high tech.
  - A chemist who does not do too chemistry stuff.
 
content:
  - title: Research Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Charge Screening Effects in P3HT:Ionic Liquid Blends
#         link: https://github.com/Beandope/UV_and_PL
#         link_text: Link Text
        additional_links:
          - title: Codes for data analysis and visulization
            icon: fab fa-github
            url: https://github.com/Beandope/UV_and_PL
#         quote: >
#           Short overview of the project (optional)
        description: | # this will include new lines to allow paragraphs
          This work focuses on understanding the charge screening effects in the blended pi-conjugated polymer systems. P3HTs are one of the classical material templates 
          used for testing the electronic and optical properties of polymer semiconductors. Here, the P3HTs are blended with ionic liquid, as prepared by Seong-Min Kim, 
          a previous postdoc from [Dr. Stingelin lab](http://stingelin-lab.gatech.edu). The blended solutions are casted at different temperatures to control the polymer-ionic
          liquid mixing:
          - Performed steady-state and temperature-dependent PL to examine the exciton interchain interactions and bandwidths.
          - Developed a Python script based on Franck-Condon progression to simulate and extract essential spectral parameters.
          - Conducted TCSPC and Fluorescence Upconversion measurements to investigate the exciton dynamics from femto-microsecond time range.
          - Built an extended free-space beam path for the ability to measure time-resolved PL under a large range of temperatures.
     
  - title: Experiences
    layout: list
    content:
      - layout: right
        title: Silva Lab
        sub_title: Graduate Research Assistant
        caption: April 2019 - present
        link: https://silva.chemistry.gatech.edu
        quote: >
#           Short description of the company (optional)
        description: | # this will include new lines to allow paragraphs
          - Hands-on experiences on linear and nonlinear high harmonic generation with amplified laser systems, OPA and NOPA, to create high-power and broad-bandwidth pulses.
          - Extensive working experiences with free-space nonlinear, ultrafast spectroscopy systems, such as transient absorption (TA), time-correlated single photon counting (TCSPC), 
            fluorescence upconversion, photoluminescence (PL)-detected two-dimensional electronic spectroscopy.
          - Hands-on experiences on optical metrology measurements such as absorption and PL spectroscopy, atomic force microscopy (AFM), dynamic and static light scattering (DLS/SLS), 
            cross-polarized optical microscopy (CPOM).
          - Experiences in building simulation models in calculating optical features of organic semiconductor polymers as well as data analysis and visualization using Python.
  
  - title: 
    layout: list
    content:
      - layout: right
        title: Duhamel Lab
        sub_title: Undergraduate Research Assistant
        caption: May 2017 - present
        link: https://uwaterloo.ca/chemistry/people-profiles/jean-duhamel
#         quote: >
#            Molecular Spectroscopy, Polymer Structure Characterization Waterloo, Canada
        description: | # this will include new lines to allow paragraphs
          - Hands on experiences with organic synthesis, and purification methods such as dialysis, precipitation and freeze-dry.
          - Applied UV, steady-state and time-resolved PL to characterize the content of the dyes and the ratio of excimer to 
            monomer contributions to the total fluorescence spectra.
          - Adopted home-written Fluorescence Blob Model (FBM) to simulate and analyze the kinetics of the polymer chain movement.
  
  - title: Education
    layout: list
    content:
      - layout: right
        title: Georgia Institute of Technology
        sub_title: 
        caption: August 2018 - present
#         quote: >
#           Short institution or course description (optional)
        description: | # this will include new lines to allow paragraphs
          Ph.D. Candidate in Physical Chemistry, specialized in nonlinear, ultrafast spectroscopy, solid-state physics.
 - title: University of Waterloo
   layout: right
   
 
 
  - title: Publication
    layout: list
    content: | # this will include new lines to allow paragraphs
    
      - Venkatesh, Rahul, <Yulong Zheng>, Campbell Viersen, Aaron Liu, Carlos Silva, Martha Grover, and Elsa Reichmanis. "Data Science Guided Experiments Identify Conjugated Polymer 
        Solution Concentration as a Key Parameter in Device Performance." [ACS Materials Letters 3, no. 9 (2021): 1321-1327.](https://pubs.acs.org/doi/abs/10.1021/acsmaterialslett.1c00320)
      
      
# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
